apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web
  labels:
    app: django-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-web
  template:
    metadata:
      labels:
        app: django-web
    spec:
      containers:
        - name: django-web
          image: api_test:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
          command: ["gunicorn"]
          args: ["config.wsgi:application", "--bind", "0.0.0.0:8000"]
---
apiVersion: v1
kind: Service
metadata:
  name: django-web
  labels:
    app: django-web
spec:
  selector:
    app: django-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
